#!/usr/bin/env bash
#Transfers file from client to server

Path_to_file=$1
IP=$2
Username=$3
Path_to_SSH_key=$4
if [[ $# -lt 3 ]]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$path_to_SSH_key" "$Path_to_File" "$Username"@"$IP":~/
fi
