#!/usr/bin/env bash
# Configuring second web server

sudo apt-get update
sudo apt-get install -y nginx

sudo chmod go+w /etc/nginx/sites-available/default
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod go+w /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo touch /var/www/html/error.html
sudo chmod go+w /var/www/html/error.html
echo "Ceci n'est pas une page" > /var/www/html/error.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	add_header X-Served-By $HOSTNAME;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /error.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
